### ISSUE TITLE
Kijaa never shows up as a system

### ISSUE THREAD

**Issue by Notsonoble** [comnom/Eternals#1]
Kijaa never shows up as a system,

also I couldn't actually figure out how to get to the areas legitimately in game I ended up editing my save to find these systems.

**Comment by Notsonoble** [comment]
So i somehow only got part of the master download, re downloaded and now the system shows. I still can't figure out how someone gets here ingame.

**Comment by comnom** [comment]
>So i somehow only got part of the master download, re downloaded and now the system shows.

Glad to hear it.

>I still can't figure out how someone gets here ingame.

It's accessible by jump drive from the wanderer, hai, or kor sestor systems that border it. It's not intended to be accessed by hyper drive.
