### ISSUE TITLE
Activating Issues.

### ISSUE THREAD

**Issue by Karazura** [comnom/Eternals#4]
As far as I can tell I'm installing this plugin in the correct location with only other plugins being The Enclave by Makuta-Miras and the HIGH DPI Plugin and both of these work properly. Is there some compatibility issue that I am unaware of or am I in the wrong place or otherwise screwing up. 

File listing I'm in looks like Local Disk (C:)/Users/(USER NAME)/appdata/roaming/endlesssky/plugins like it suggests on the Steam Support page for mods.

A step by step guide for installing this would almost be nice.

**Comment by tgape** [comment]
I don't play it on Windows, so I can't say exactly where the plugin should go.  However, I found the directory I was told to put it in on Linux didn't work, either.

I looked for where my save file was stored (The filename is your player's name with '.txt' added at the end.)  The immediate parent directory to that is named saves and right beside it is a directory named plugins.  Plugins installed there work.  I don't know if that will work on Windows, also, or even all Linux distros, it's just what worked for me.

**Comment by tgape** [comment]
My comment may be helpful for other endless sky plugins, but may not be for this one - this one appears to have ceased development with its intro questline unfinished and no other story lines even started.

It looks like they put a lot of effort into it, but then they just stopped pushing updates, kind of like they started a new job and found they didn't have time for this.

**Comment by jdahg** [comment]
It _was_ very interesting up until the point that it abruptly ends.
